---
version: '3.8'

services:
    # nginx:
    #     image: nginx:latest
    #     container_name: nginx
    #     ports:
    #         - '8000:80'
    #         - '443'
    #     # volumes:
    #     #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
    #     #     - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    #     #     - ./docker/nginx/certs:/etc/nginx/certs
    #     links:
    #         - api
    #     networks:
    #         - spidertracks-net

    api:
        build:
            context: ./
            dockerfile: ./docker/base/Dockerfile.local
        image: spidertracks-api
        container_name: spidertracks-api
        restart: always
        volumes:
            - .:/application
            - ~/.aws:/home/expressjs/.aws
        links:
            - db_customers
        ports:
            - '8080:6000'
            - '9229:9229' # Needed for vscode debugger :)
        command: ['yarn', 'run', 'start']
        networks:
            - spidertracks-net

    db_customers:
        image: postgres:14
        container_name: db_customers
        volumes:
            - ./data/db_customers:/var/lib/postgresql/data
        restart: always
        ports:
            - '5430:5432'
        environment:
            - POSTGRES_DB=spidertracks
            - POSTGRES_USER=spidertracks
            - POSTGRES_PASSWORD=secret
        networks:
            - spidertracks-net

networks:
    spidertracks-net:
